mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: placeholde
    MYSQL_USER: placeholde
    MYSQL_PASSWORD: placeholde

todoapp:
  namespace: todoapp
  image:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: placeholde
    DB_NAME: placeholde
    DB_USER: placeholde
    DB_PASSWORD: placeholde
    DB_HOST: placeholde

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"