name: Django CI

run-name: Run by ${{ github.actor }} on commit ${{ github.sha }}

on:
  push:
    branches:
      - main
      - d4vp4
  pull_request:
    branches:
      - main
      - d4vp4
  workflow_dispatch:
    inputs:
      artifact_choice:
        description: 'Choose artifact to deploy (format: os-pythonversion)'
        required: true
        default: 'ubuntu-latest-3.9'
        type: choice
        options:
          - ubuntu-latest-3.8
          - ubuntu-latest-3.9
          - windows-latest-3.8
          - windows-latest-3.9

env:
  DOCKER_IMAGE_NAME: 'd4vp4/todo-app'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    name: Python CI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src/requirements.txt
          python -m pip install coverage flake8

      - name: Run Tests and Generate Coverage
        run: |
          cd src
          python -m coverage run manage.py test
          python -m coverage report

      - name: Check Code Style
        continue-on-error: true
        run: flake8 src

      - name: Check Complexity
        continue-on-error: true
        run: flake8 src --max-complexity=10 --exit-zero

      - name: Upload Codebase
        uses: actions/upload-artifact@v4
        with:
          name: codebase-${{ matrix.os }}-${{ matrix.python-version }}
          path: .
          include-hidden-files: true

  docker-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    environment: development

    steps:
      - name: Set Artifact Name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ARTIFACT_NAME=codebase-${{ inputs.artifact_choice }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=codebase-ubuntu-latest-3.9" >> $GITHUB_ENV
          fi

      - name: Download Codebase
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }},${{ env.DOCKER_IMAGE_NAME }}:latest

  helm-ci:
    runs-on: ubuntu-latest
    needs: python-ci

    steps:
      - name: Set Artifact Name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ARTIFACT_NAME=codebase-${{ inputs.artifact_choice }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=codebase-ubuntu-latest-3.9" >> $GITHUB_ENV
          fi

      - name: Download Codebase
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Helm Template
        run: helm template ./helm-charts/todoapp

      - name: Helm Lint
        run: helm lint ./helm-charts/todoapp

      - name: Helm Package
        run: helm package ./helm-charts/todoapp

      - name: Upload Helm Chart
        uses: actions/upload-artifact@v4
        with:
          name: helm-package
          path: "*.tgz"

  deploy-development:
    needs: [docker-ci, helm-ci]
    uses: ./.github/workflows/reusable-deployment.yml
    environment: development
    with:
      environment: development
      image_tag: ${{ github.sha }}
      docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}

  deploy-staging:
    needs: deploy-development
    uses: ./.github/workflows/reusable-deployment.yml
    environment: staging
    with:
      environment: staging
      image_tag: ${{ github.sha }}
      docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}